version: '2'
services:
    prometheus:
        image: prom/prometheus
        ports:
            - "9090:9090"
        volumes:
            - $GOPATH/src/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

    grafana:
        image: grafana/grafana
        ports:
            - "3000:3000"
        environment:
            - GF_SERVER_ROOT_URL=http://docker
            - GF_SECURITY_ADMIN_PASSWORD=admin
        links:
            - prometheus
